#ifndef DYNDXT_LOADER_XBDM_ERR_H
#define DYNDXT_LOADER_XBDM_ERR_H

#ifdef __cplusplus
extern "C" {
#endif

#define FACILITY_XBOX 0x2DB

#define XBOX_SUCCESS(code) (((code)&0x80000000) == 0)

#define DEF_SUCCESS(code) ((FACILITY_XBOX << 16) + (code))
#define DEF_ERROR(code) (0x80000000 + (FACILITY_XBOX << 16) + (code))

#define XBOX_S_OK DEF_SUCCESS(0x00)
#define XBOX_S_MULTILINE DEF_SUCCESS(0x02)
#define XBOX_S_BINARY DEF_SUCCESS(0x03)
#define XBOX_S_SEND_BINARY DEF_SUCCESS(0x04)
#define XBOX_S_DEDICATED DEF_SUCCESS(0x05)

// This seems to be used to terminate multiline responses, despite arguably
// being successful.
#define XBOX_S_NO_MORE_DATA DEF_ERROR(0x104)

#define XBOX_E_UNEXPECTED DEF_ERROR(0x00)
#define XBOX_E_MAX_CONNECTIONS_EXCEEDED DEF_ERROR(0x01)
#define XBOX_E_FILE_NOT_FOUND DEF_ERROR(0x02)
#define XBOX_E_NO_SUCH_MODULE DEF_ERROR(0x03)
#define XBOX_E_MEMORY_NOT_MAPPED DEF_ERROR(0x04)
#define XBOX_E_FAIL DEF_ERROR(0x05)
#define XBOX_E_UNKNOWN_COMMAND DEF_ERROR(0x07)
#define XBOX_E_NOT_STOPPED DEF_ERROR(0x08)
#define XBOX_E_FILE_MUST_BE_COPIED DEF_ERROR(0x09)
#define XBOX_E_EXISTS DEF_ERROR(0x0A)
#define XBOX_E_DIRECTORY_NOT_EMPTY DEF_ERROR(0x0B)
#define XBOX_E_FILENAME_INVALID DEF_ERROR(0x0C)
#define XBOX_E_CREATE_FILE_FAILED DEF_ERROR(0x0D)
#define XBOX_E_ACCESS_DENIED DEF_ERROR(0x0E)
#define XBOX_E_TYPE_INVALID DEF_ERROR(0x11)
#define XBOX_E_DATA_NOT_AVAILABLE DEF_ERROR(0x12)
#define XBOX_E_DEDICATED_CONNECTION_REQUIRED DEF_ERROR(0x16)

#ifdef __cplusplus
}  // extern "C"
#endif

#endif  // DYNDXT_LOADER_XBDM_ERR_H
